[theme]
base = "light"
primaryColor = "#648f3f"
backgroundColor = "#eef0fa"
secondaryBackgroundColor = "#c8c6eb"
textColor = "#1f254f"
font = "sans serif"

[server]
runOnSave = true
fileWatcherType = "poll"
